"""removed unique date constraint in workout

Revision ID: 3af2af5d043f
Revises: 2ab8488a6575
Create Date: 2023-10-26 11:23:20.453631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3af2af5d043f'
down_revision: Union[str, None] = '2ab8488a6575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_date_constraint', 'workout', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_date_constraint', 'workout', ['date'])
    # ### end Alembic commands ###
