"""fixing relations conflict

Revision ID: e51d14c77161
Revises: 9e932fbd5bf0
Create Date: 2023-10-25 09:10:50.583786

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e51d14c77161'
down_revision: Union[str, None] = '9e932fbd5bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
